#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "terraforming-mars"
name = "Terraforming Mars "
description.en = "Open-source online implementation of the great board game Terraforming mars."
description.fr = "Implementation en ligne à code source ouvert de l’excellent jeu de plateau Terraforming Mars"

version = "2023.12.29~ynh1"

maintainers = ["Thovi98"]

[upstream]
license = "GPL-3.0"
demo = "https://terraforming-mars.herokuapp.com/"
code = "https://github.com/terraforming-mars/terraforming-mars"

[integration]
yunohost = ">= 11.2.4"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/example"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

 [resources]

    [resources.sources]

      [resources.sources.main]
        url = "https://github.com/terraforming-mars/terraforming-mars/archive/5c0ec8d199d8dc0c7e8990905e60bb457f33f009.tar.gz"
        sha256 = "7a96b4c1af57361cbca4efe8a77e73331223423ffb0741d64f20e64218dcfe72"
        in_subdir = true
        autoupdate.strategy = "latest_github_commit"
   
    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]

    main.url = "/"

    [resources.ports]
    main.default = 8080

    [resources.apt]
    packages = "postgresql, postgresql-contrib"
       
    [resources.database]
    type = "postgresql"
