#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "terraforming_mars"
name = "Terraforming Mars "
description.en = "Open-source online implementation of the great board game Terraforming mars."
description.fr = "Implementation en ligne à code source ouvert de l’excellent jeu de plateau Terraforming Mars"

version = "0.01~ynh1"

maintainers = ["Thovi98"]

[upstream]
license = "GPL-3.0"
demo = "https://terraforming-mars.herokuapp.com/"
code = "https://github.com/terraforming-mars/terraforming-mars"

[integration]
yunohost = ">= 11.2.4"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/example"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

 [resources]
      [resources.sources]

        [resources.sources.main]
        url = "https://github.com/terraforming-mars/terraforming-mars/archive/686fa15abaa69dccfe4d8a9e91bf077978b7ae20.zip"
        sha256 = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"

        # These infos are used by https://github.com/YunoHost/apps/blob/master/tools/autoupdate_app_sources/autoupdate_app_sources.py
        # to auto-update the previous asset urls and sha256sum + manifest version
        # assuming the upstream's code repo is on github and relies on tags or releases
        # See the 'sources' resource documentation for more details

        # autoupdate.strategy = "latest_github_tag"

    [resources.system_user]
    # This will provision/deprovision a unix system user

    [resources.install_dir]
    # This will create/remove the install dir as /var/www/$app
    # and store the corresponding setting $install_dir

    [resources.data_dir]
    # This will create/remove the data dir as /home/yunohost.app/$app
    # and store the corresponding setting $data_dir

    [resources.permissions]
    # This will configure SSOwat permission for $domain/$path/
    # The initial allowed group of user is configured via the init_main_permission question (public=visitors, private=all_users)
    main.url = "/"

    [resources.ports]
    # This will pick a random port for reverse-proxying and store it as the $port setting

    [resources.apt]
    # This will automatically install/uninstall the following apt packages
    # and implicitly define the $phpversion setting as 8.0 (if phpX.Y-foobar dependencies are listed)
    packages = "deb1, deb2, php8.0-foo, php8.0-bar"

    [resources.database]
    # This will automatically provision/deprovison a MySQL DB and store the corresponding credentials in settings $db_user, $db_name, $db_pwd
    type = "mysql"
